background #000000
foreground #ffffff

font_family JetBrains Mono
font_size 11

cursor #ffffff

window_padding_width 10
background_opacity 0.55

enable_audio_bell no

confirm_os_window_close 0

include ~/.cache/wallust/kitty.conf
