general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1

    col.active_border = rgba(000000ee)
    col.inactive_border = rgba(111111aa)
}

animations {
    enabled = true
    bezier = fast, 0.05, 0.9, 0.1, 1.0

    animation = windows, 1, 5, fast
    animation = fade, 1, 5, fast
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

input {
    kb_layout = br
    kb_variant = abnt2
}

decoration {
    rounding = 12 

    blur {
        enabled = true
        size = 3
        passes = 2
    }
}

exec-once = waybar
exec-once = nm-applet
exec-once = awww-daemon
exec-once = swaync

bind = , Print, exec, grim -g "$(slurp)" ~/Imagens/print-$(date +%Y%m%d-%H%M%S).png
bind = SUPER, RETURN, exec, kitty
bind = SUPER, D, exec, wofi --show drun
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, F, fullscreen

bind = SUPER, E, exec, dolphin
bind = SUPER, B, exec, firefox
bind = SUPER, V, exec, steam
bind = SUPER, S, exec, flatpak run com.spotify.Client
bind = SUPER, A, exec, kitty -e btop
bind = SUPER, P, exec, gtk-launch sklauncher
bind = SUPER, T, exec, ~/.local/bin/theme

bind = SUPER, SPACE, togglefloating
bind = SUPER, C, exec, swaync-client -t

bind = SUPER SHIFT, K, swapwindow, l
bind = SUPER SHIFT, L, swapwindow, r
bind = SUPER, K, movefocus, l
bind = SUPER, L, movefocus, r

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
